import { CATALOG } from './catalog.js';

export const HUMAN_FILES = {
  "千千哥哥": {
    "互动表情": "skins/human/lumi-brother/01-互动.gif",
    "待机": "skins/human/lumi-brother/02-待机.gif",
    "向左走": "skins/human/lumi-brother/03-向左走.gif",
    "向右走": "skins/human/lumi-brother/04-向右走.gif",
    "睡觉": "skins/human/lumi-brother/05-睡觉.gif",
    "敲代码": "skins/human/lumi-brother/06-敲代码.gif",
    "吃饭": "skins/human/lumi-brother/07-吃饭.gif",
    "开心蹦蹦": "skins/human/lumi-brother/08-开心蹦蹦.gif",
    "害羞": "skins/human/lumi-brother/09-害羞.gif",
    "摸摸头": "skins/human/lumi-brother/10-摸摸头.gif",
    "打招呼": "skins/human/lumi-brother/11-打招呼.gif",
    "打哈欠": "skins/human/lumi-brother/12-打哈欠.gif",
    "跳舞": "skins/human/lumi-brother/13-跳舞.gif",
    "摔趴趴": "skins/human/lumi-brother/14-摔趴趴.gif",
    "互动_写日记": "skins/human/lumi-brother/15-写日记.gif",
    "掉落": "skins/human/lumi-brother/16-掉落.gif",
    "打滚": "skins/human/lumi-brother/17-打滚.gif",
    "比心": "skins/human/lumi-brother/18-比心.gif",
    "向左看": "skins/human/lumi-brother/19-向左看.gif",
    "向右看": "skins/human/lumi-brother/20-向右看.gif",
    "听音乐": "skins/human/lumi-brother/21-听音乐.gif"
  },
  "梨梨哥哥": {
    "互动表情": "skins/human/baichuan/互动.gif",
    "互动_写日记": "skins/human/baichuan/写日记.gif",
    "吃饭": "skins/human/baichuan/吃饭.gif",
    "向右看": "skins/human/baichuan/向右看.gif",
    "向右走": "skins/human/baichuan/向右走.gif",
    "向左看": "skins/human/baichuan/向左看.gif",
    "向左走": "skins/human/baichuan/向左走.gif",
    "听音乐": "skins/human/baichuan/听音乐.gif",
    "害羞": "skins/human/baichuan/害羞.gif",
    "开心蹦蹦": "skins/human/baichuan/开心蹦蹦.gif",
    "待机": "skins/human/baichuan/默认待机.gif",
    "打哈欠": "skins/human/baichuan/打哈欠.gif",
    "打招呼": "skins/human/baichuan/打招呼.gif",
    "打滚": "skins/human/baichuan/打滚.gif",
    "掉落": "skins/human/baichuan/掉落.gif",
    "摔趴趴": "skins/human/baichuan/摔趴趴.gif",
    "摸摸头": "skins/human/baichuan/摸摸头.gif",
    "敲代码": "skins/human/baichuan/敲代码.gif",
    "比心": "skins/human/baichuan/比心.gif",
    "睡觉": "skins/human/baichuan/睡觉.gif",
    "跳舞": "skins/human/baichuan/跳舞.gif"
  },
  "梨梨兔兔": {
    "互动_写日记": "skins/human/qili/写日记.gif",
    "吃饭": "skins/human/qili/吃饭.gif",
    "向右看": "skins/human/qili/向右看.gif",
    "向右走": "skins/human/qili/向右走.gif",
    "向左看": "skins/human/qili/向左看.gif",
    "向左走": "skins/human/qili/向左走.gif",
    "听音乐": "skins/human/qili/听音乐.gif",
    "害羞": "skins/human/qili/害羞.gif",
    "开心蹦蹦": "skins/human/qili/开心蹦蹦.gif",
    "待机": "skins/human/qili/默认待机.gif",
    "打哈欠": "skins/human/qili/打哈欠.gif",
    "打招呼": "skins/human/qili/打招呼.gif",
    "打滚": "skins/human/qili/打滚.gif",
    "抱玩偶": "skins/human/qili/抱玩偶.gif",
    "掉落": "skins/human/qili/掉落.gif",
    "摔趴趴": "skins/human/qili/摔趴趴.gif",
    "摸摸头": "skins/human/qili/摸摸头.gif",
    "敲代码": "skins/human/qili/敲代码.gif",
    "比心": "skins/human/qili/比心.gif",
    "睡觉": "skins/human/qili/睡觉.gif",
    "跳舞": "skins/human/qili/跳舞.gif"
  },
  "千千猫猫": {
    "互动_写日记": "skins/human/lumi/写日记.gif",
    "吃饭": "skins/human/lumi/吃饭.gif",
    "向右看": "skins/human/lumi/向右看.gif",
    "向右走": "skins/human/lumi/向右走.gif",
    "向左看": "skins/human/lumi/向左看.gif",
    "向左走": "skins/human/lumi/向左走.gif",
    "听音乐": "skins/human/lumi/听音乐.gif",
    "害羞": "skins/human/lumi/害羞.gif",
    "开心蹦蹦": "skins/human/lumi/开心蹦蹦.gif",
    "待机": "skins/human/lumi/待机.gif",
    "打哈欠": "skins/human/lumi/打哈欠.gif",
    "打招呼": "skins/human/lumi/打招呼.gif",
    "打滚": "skins/human/lumi/打滚.gif",
    "掉落": "skins/human/lumi/掉落.gif",
    "摔趴趴": "skins/human/lumi/摔趴趴.gif",
    "摸摸头": "skins/human/lumi/摸摸头.gif",
    "敲代码": "skins/human/lumi/敲代码.gif",
    "比心": "skins/human/lumi/比心.gif",
    "睡觉": "skins/human/lumi/睡觉.gif",
    "跳舞": "skins/human/lumi/跳舞.gif"
  },
  "砂金": {
    "互动表情": "skins/human/aventurine/01-互动.gif",
    "待机": "skins/human/aventurine/02-待机.gif",
    "向左走": "skins/human/aventurine/03-向左走.gif",
    "向右走": "skins/human/aventurine/04-向右走.gif",
    "睡觉": "skins/human/aventurine/05-睡觉.gif",
    "敲代码": "skins/human/aventurine/06-敲代码.gif",
    "吃饭": "skins/human/aventurine/07-吃饭.gif",
    "开心蹦蹦": "skins/human/aventurine/08-开心蹦蹦.gif",
    "害羞": "skins/human/aventurine/09-害羞.gif",
    "摸摸头": "skins/human/aventurine/10-摸摸头.gif",
    "打招呼": "skins/human/aventurine/11-打招呼.gif",
    "打哈欠": "skins/human/aventurine/12-打哈欠.gif",
    "跳舞": "skins/human/aventurine/13-跳舞.gif",
    "摔趴趴": "skins/human/aventurine/14-摔趴趴.gif",
    "互动_写日记": "skins/human/aventurine/15-写日记.gif",
    "掉落": "skins/human/aventurine/16-掉落.gif",
    "打滚": "skins/human/aventurine/17-打滚.gif",
    "比心": "skins/human/aventurine/18-比心.gif",
    "向左看": "skins/human/aventurine/19-向左看.gif",
    "向右看": "skins/human/aventurine/20-向右看.gif",
    "听音乐": "skins/human/aventurine/21-听音乐.gif"
  }
};
export const HUMAN_COMBOS = {
  "梨梨兔兔-梨梨哥哥": "skins/human/baichuan/贴贴.gif",
  "梨梨兔兔-梨梨哥哥_2": "skins/human/baichuan/叠叠乐.gif",
  "千千猫猫-梨梨兔兔": "skins/human/lumi/贴贴.gif",
  "千千猫猫-梨梨兔兔_2": "skins/human/lumi/叠叠乐.gif"
};
const ORIGINAL_ONLY = [{id:'original',label:'原版皮肤'}];
export const builtinOptions = name => Object.hasOwn(HUMAN_FILES,name)
  ? [{id:'human',label:'人形皮肤（默认）'},...(name==='砂金'?[]:[{id:'original',label:'原版像素皮肤'}])]
  : Object.hasOwn(CATALOG.pets,name)?ORIGINAL_ONLY:[];
export const builtinId = (settings,name) => builtinOptions(name).some(o=>o.id===settings?.builtinSkins?.[name])
  ? settings.builtinSkins[name] : builtinOptions(name)[0]?.id;
export function normalizeBuiltins(value={}){
  const builtinSkins={};for(const name of Object.keys(CATALOG.pets))builtinSkins[name]=builtinId({builtinSkins:value},name);return builtinSkins;
}
export function selectBuiltin(settings,name,id){
  if(!builtinOptions(name).some(o=>o.id===id))throw Error('没有这套内置皮肤。');
  (settings.builtinSkins??={})[name]=id;
}
const asset = path => new URL('assets/'+path.split('/').map(encodeURIComponent).join('/'),import.meta.url).href;
export function builtinPetAsset(settings,name,action){
  if(builtinId(settings,name)!=='human')return null;
  const files=HUMAN_FILES[name];return asset(files[action]||files['待机']);
}
export function builtinComboAsset(settings,key){
  const file=HUMAN_COMBOS[key];if(!file)return null;
  return key.split('_')[0].split('-').every(name=>builtinId(settings,name)==='human')?asset(file):null;
}

export const ORIGINAL_ACTIONS = {
  "千千猫猫": [
    "待机",
    "向左走",
    "向右走",
    "睡觉",
    "敲代码",
    "吃饭",
    "开心蹦蹦",
    "害羞",
    "摸摸头",
    "打招呼",
    "打哈欠",
    "跳舞",
    "摔趴趴",
    "互动_写日记",
    "掉落",
    "打滚",
    "向左看",
    "向右看"
  ],
  "梨梨兔兔": [
    "待机",
    "向左走",
    "向右走",
    "睡觉",
    "敲代码",
    "吃饭",
    "开心蹦蹦",
    "害羞",
    "摸摸头",
    "打招呼",
    "打哈欠",
    "跳舞",
    "摔趴趴",
    "互动_写日记",
    "掉落",
    "打滚",
    "比心",
    "向左看",
    "向右看"
  ],
  "千千哥哥": [
    "待机",
    "向左走",
    "向右走",
    "睡觉",
    "敲代码",
    "吃饭",
    "开心蹦蹦",
    "害羞",
    "摸摸头",
    "打招呼",
    "打哈欠",
    "跳舞",
    "摔趴趴",
    "互动_写日记",
    "掉落",
    "打滚",
    "比心",
    "点赞",
    "向左看",
    "向右看"
  ],
  "梨梨哥哥": [
    "待机",
    "向左走",
    "向右走",
    "睡觉",
    "敲代码",
    "吃饭",
    "开心蹦蹦",
    "害羞",
    "摸摸头",
    "打招呼",
    "打哈欠",
    "跳舞",
    "摔趴趴",
    "互动_写日记",
    "掉落",
    "打滚",
    "比心",
    "点赞",
    "向左看",
    "向右看"
  ],
  "煤球猫猫": [
    "待机",
    "向左走",
    "向右走",
    "睡觉",
    "敲代码",
    "吃饭",
    "开心蹦蹦",
    "害羞",
    "打招呼",
    "打哈欠",
    "跳舞",
    "摔趴趴",
    "互动_写日记",
    "掉落",
    "比心",
    "向左看",
    "向右看"
  ],
  "酒酒狐狸": [
    "待机",
    "万圣节",
    "专注",
    "互动_写日记",
    "冒冷汗",
    "冲鸭",
    "吃饭",
    "向右看",
    "向右走",
    "向左看",
    "向左走",
    "吓一跳",
    "哈哈哈",
    "国庆",
    "圣诞",
    "好耶",
    "害羞",
    "开心蹦蹦",
    "待机_下雪",
    "待机_冬",
    "待机_夏",
    "待机_多云",
    "待机_大雨",
    "待机_春",
    "待机_晴夜",
    "待机_晴天",
    "待机_毛毛雨",
    "待机_炎热",
    "待机_秋",
    "待机_阴天",
    "待机_降温",
    "待机_雨天",
    "待机_雷雨",
    "待机_雾",
    "打哈欠",
    "打招呼",
    "掉落",
    "摔趴趴",
    "撒花",
    "敲代码",
    "春节",
    "比心",
    "犯困向右走",
    "犯困向左走",
    "生日",
    "看视频",
    "睡觉",
    "纪念日",
    "跳舞",
    "转圈圈"
  ],
  "灰鸮g老师": [
    "待机",
    "向左走",
    "向右走",
    "睡觉",
    "敲代码",
    "吃饭",
    "开心蹦蹦",
    "害羞",
    "打招呼",
    "打哈欠",
    "跳舞",
    "摔趴趴",
    "互动_写日记",
    "掉落",
    "向左看",
    "向右看",
    "互动_扶眼镜1",
    "互动_看书"
  ],
  "陈野": [
    "发呆",
    "爬爬_向左",
    "爬爬_向右",
    "趴着睡",
    "打工中",
    "吃饭团",
    "开心",
    "害羞捂脸",
    "嗨",
    "摸摸头",
    "举爪爪",
    "打哈欠",
    "转圈圈",
    "哼",
    "聊天中",
    "被敲头",
    "打滚",
    "比心",
    "摇尾巴",
    "扭头",
    "听歌",
    "惊醒"
  ]
};
